datadir: fix UserAccount class structure
There are different names of some fields in auto-generated file
'accounts.json' and UserAccount class. It causes a failure of
user accounts import [1].
Fix this issue.

[1]
--------------------------------------------------------------------------
2020-10-18 18:38:04 INFO     datadir                                  taxer-api url 'http://127.0.0.1:7080'
Traceback (most recent call last):
  File "main.py", line 47, in <module>
    acc = d.UserAccounts(userid)
  File "/home/cryo/src/github/py-pbank-statements/datadir.py", line 138, in UserAccounts
    return UserAccounts(schema().load(accounts_json, many=True, partial=True, unknown=RAISE))
  File "/home/cryo/.local/lib/python3.8/site-packages/marshmallow_dataclass/__init__.py", line 544, in load
    all_loaded = super().load(data, many=many, **kwargs)
  File "/home/cryo/.local/lib/python3.8/site-packages/marshmallow/schema.py", line 723, in load
    return self._do_load(
  File "/home/cryo/.local/lib/python3.8/site-packages/marshmallow/schema.py", line 905, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {0: {'tf_bank_corr_account': ['Unknown field.'], 'tf_bank_corr': ['Unknown field.'], 'tf_bank_place': ['Unknown field.'], 'tf_bank_corr_swift': ['Unknown field.'], 'tf_bank_corr_place': ['Unknown field.'], 'tf_bank_swift': ['Unknown field.']}, 1: {'tf_bank_corr_account': ['Unknown field.'], 'tf_bank_corr': ['Unknown field.'], 'tf_bank_place': ['Unknown field.'], 'tf_bank_corr_swift': ['Unknown field.'], 'tf_bank_corr_place': ['Unknown field.'], 'tf_bank_swift': ['Unknown field.']}}

Signed-off-by: Oleksandr Suvorov <oleksandr.suvorov@toradex.com>